name = "gamingandmusic"
type = "service"
main = "dist/index.js"
compatibility_date = "2024-09-19"

[env.production]
name = "gamingandmusic-prod"
routes = [
  { pattern = "gamingandmusic.com/*", zone_name = "gamingandmusic.com" }
]

[build]
command = "npm run build"
cwd = "./"
watch_paths = ["app/**/*.{js,jsx,ts,tsx}"]

[[env.production.triggers.crons]]
cron = "0 0 * * *"